### PR TITLE
Refactor repo to be BLUI

### PR DESCRIPTION
**Pull request by emclaug2**
#### Changes proposed in this Pull Request:
- This marks the first @brightlayer-ui package migration.  
- This can be reviewed for accuracy, but probably shouldn't be merged in until we have an NPM account setup so that ci can publish it.

### CODE REVIEW

**Comment by emclaug2** [comment]
Thankfully this package does not require majorVersion & majorVersion-1 changes since it's on version 1.X.X

**Comment by jeffvg** [comment]
> #### Changes proposed in this Pull Request:
> * This marks the first @brightlayer-ui package migration.
> * This can be reviewed for accuracy, but probably shouldn't be merged in until we have an NPM account setup so that ci can publish it.

looking at NPM account setup now

**Comment by jeffvg** [comment]
@emclaug2 NPM account is set. Notes in wiki

**Comment by emclaug2** [comment]
I've made an access token so our CI is ready to publish for this repo.  This PR can probably go to master today if it's looking good.

**Review by daileytj — APPROVED** [review]

**Review by jeffvg — APPROVED** [review]
seems good to me

**Pull request merged**
