### PR TITLE
Master

### PR DESCRIPTION
**Pull request by emclaug2**
#### Changes proposed in this Pull Request:
- Publish v1.0.2 of the @pxblue/tag script.

### CODE REVIEW

**Comment by emclaug2** [comment]
Even though dev is failing this build should be fine; dev will continue to fail until the latest tag script is published.

**Comment by emclaug2** [comment]
Even once this branch gets merged in, I'm expecting the first build to fail since "tag @pxblue/publish" step will use an older version of the @pxblue/tag script.  I'll just re-run the failed part, and it'll use pass using the latest @pxblue/tag script.

**Review by huayunh — APPROVED** [review]
I trust you although I have no idea whats happening here

**Comment by joebochill** [comment]
Shouldn't the tag job be tagging itself with the latest local code, not what's published to NPM?

**Comment by emclaug2** [comment]
> Shouldn't the tag job be tagging itself with the latest local code, not what's published to NPM?

Right now the tag job is using the latest published version for both the packages.  I think we kept these scripts all the same just for consistency across the repos.

**Comment by joebochill** [comment]
> > Shouldn't the tag job be tagging itself with the latest local code, not what's published to NPM?
> 
> Right now the tag job is using the latest published version for both the packages. I think we kept these scripts all the same just for consistency across the repos.

I think I commented on this on the original PR for this exact use case. Tagging in this repo is always going to be using a version that lags behind the current code if we pull from npm (unless we are publishing a new version because the publish step will happen before the tag)

**Comment by emclaug2** [comment]
> I think I commented on this on the original PR for this exact use case. Tagging in this repo is always going to be using a version that lags behind the current code if we pull from npm (unless we are publishing a new version because the publish step will happen before the tag)

I just opened a PR that'll use the local version of the @pxblue/tag script.

**Comment by emclaug2** [comment]
Let's include the tag-suffix update in this master merge.

**Comment by joebochill** [comment]
PR direction was backwards...need a new PR to go the right way

**Pull request closed without merging**
